/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package landing;

import java.util.ArrayList;
import javax.swing.*;


/**
 *
 * @author Track Computers
 */
public class managerwork extends javax.swing.JFrame {

    /**
     * Creates new form managerwork
     */
    public managerwork() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        editEmp = new javax.swing.JMenuItem();
        editacc = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        issueAcc = new javax.swing.JMenuItem();
        Sign = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        addE = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        seeRequest = new javax.swing.JMenuItem();
        checkSign = new javax.swing.JMenuItem();
        open = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        checkReq = new javax.swing.JMenuItem();
        availTngs = new javax.swing.JMenuItem();
        singleEmplo = new javax.swing.JMenuItem();
        list = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Do your work Here!!");

        jMenu2.setText("Edit");

        editEmp.setText("employee profile");
        editEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmpActionPerformed(evt);
            }
        });
        jMenu2.add(editEmp);

        editacc.setText("accessory Data");
        editacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editaccActionPerformed(evt);
            }
        });
        jMenu2.add(editacc);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Manage");

        issueAcc.setText("issue Accessory");
        issueAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueAccActionPerformed(evt);
            }
        });
        jMenu3.add(issueAcc);

        Sign.setText("take signature");
        Sign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignActionPerformed(evt);
            }
        });
        jMenu3.add(Sign);

        jMenuItem2.setText("Remove Employee");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        addE.setText("Add Employee");
        addE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEActionPerformed(evt);
            }
        });
        jMenu3.add(addE);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("File");

        seeRequest.setText("see Requet");
        seeRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeRequestActionPerformed(evt);
            }
        });
        jMenu4.add(seeRequest);

        checkSign.setText("check Signature");
        checkSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSignActionPerformed(evt);
            }
        });
        jMenu4.add(checkSign);

        open.setText("open");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        jMenu4.add(open);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("View");

        checkReq.setText("check any request");
        jMenu5.add(checkReq);

        availTngs.setText("check availible things");
        availTngs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availTngsActionPerformed(evt);
            }
        });
        jMenu5.add(availTngs);

        singleEmplo.setText("check detail of single Employee");
        singleEmplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleEmploActionPerformed(evt);
            }
        });
        jMenu5.add(singleEmplo);

        list.setText("check list");
        list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listActionPerformed(evt);
            }
        });
        jMenu5.add(list);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(jLabel1)
                .addContainerGap(262, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(119, 119, 119))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
     crud c=new crud();
     c.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listActionPerformed
        // TODO add your handling code here:
        List l=new List();
        l.setVisible(true);
    }//GEN-LAST:event_listActionPerformed

    private void editEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmpActionPerformed
        // TODO add your handling code here:
        crud c=new crud();
     c.setVisible(true);
    }//GEN-LAST:event_editEmpActionPerformed

    private void addEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEActionPerformed
        // TODO add your handling code here:
         crud c=new crud();
     c.setVisible(true);
    }//GEN-LAST:event_addEActionPerformed

    private void issueAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueAccActionPerformed
        // TODO add your handling code here:
          JFrame d=new JFrame();
         String f= JOptionPane.showInputDialog("hi Manager,enter the name of accessory "
         +"which you are going to issue ");
         JOptionPane.showMessageDialog(d,"Accesory is issued successfully");

    }//GEN-LAST:event_issueAccActionPerformed

    private void singleEmploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleEmploActionPerformed
        // TODO add your handling code here:
        JFrame d=new JFrame();
        accessoryManager a1=new accessoryManager();
         java.util.List<String> Employee = new ArrayList<String>();
        JOptionPane.showMessageDialog(d,
  " employee name, id and phone number are listed respectively:"+a1.fillData(Employee));
    }//GEN-LAST:event_singleEmploActionPerformed

    private void availTngsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availTngsActionPerformed
        // TODO add your handling code here:
         JFrame d=new JFrame();
        accessoryManager a1=new accessoryManager();
         java.util.List<String> Accessory = new ArrayList<String>();
        JOptionPane.showMessageDialog(d,"avalible accessories are:"
        +a1.fillaData(Accessory));
    }//GEN-LAST:event_availTngsActionPerformed

    private void editaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editaccActionPerformed
        // TODO add your handling code here:
        JFrame d=new JFrame();
        accessoryManager a1=new accessoryManager();
         java.util.List<String> Accessory = new ArrayList<String>();
        JOptionPane.showMessageDialog(d,
       "Enter the accessories name in which you wanted to make changes");
        JOptionPane.showMessageDialog(d,"changes made successfully");
    }//GEN-LAST:event_editaccActionPerformed

    private void SignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignActionPerformed
        // TODO add your handling code here:
        JFrame d=new JFrame();
        credientials c=new credientials();
       JOptionPane.showMessageDialog(d,"sign of employee is"+ c.getsign());
    }//GEN-LAST:event_SignActionPerformed

    private void seeRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeRequestActionPerformed
        // TODO add your handling code here:
        JFrame d=new JFrame();
        JOptionPane.showMessageDialog(d,"There is no any request,yet");
    }//GEN-LAST:event_seeRequestActionPerformed

    private void checkSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSignActionPerformed
        // TODO add your handling code here:
        JFrame d=new JFrame();
        JOptionPane.showMessageDialog(d,"signature of Employee ali is 'A'"
        +"signature of Employee ali is 'Ah'");
    }//GEN-LAST:event_checkSignActionPerformed

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        // TODO add your handling code here:
        String g= JOptionPane.showInputDialog("Enter the name of Employee whose"
                + " profile you want to open ");
    }//GEN-LAST:event_openActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Sign;
    private javax.swing.JMenuItem addE;
    private javax.swing.JMenuItem availTngs;
    private javax.swing.JMenuItem checkReq;
    private javax.swing.JMenuItem checkSign;
    private javax.swing.JMenuItem editEmp;
    private javax.swing.JMenuItem editacc;
    private javax.swing.JMenuItem issueAcc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuItem list;
    private javax.swing.JMenuItem open;
    private javax.swing.JMenuItem seeRequest;
    private javax.swing.JMenuItem singleEmplo;
    // End of variables declaration//GEN-END:variables
}
